// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorldLogin.proto

package com.wq.entity.protobuf;

public final class WorldLogin {
  private WorldLogin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.wq.entity.protobuf.WorldLogin.worldLoginReq);
    registry.add(com.wq.entity.protobuf.WorldLogin.worldLoginRes);
  }
  public interface WorldLoginReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional int32 type = 3;
    /**
     * <code>optional int32 type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>optional int32 type = 3;</code>
     */
    int getType();

    // optional int32 onlineCount = 4;
    /**
     * <code>optional int32 onlineCount = 4;</code>
     */
    boolean hasOnlineCount();
    /**
     * <code>optional int32 onlineCount = 4;</code>
     */
    int getOnlineCount();
  }
  /**
   * Protobuf type {@code com.wq.entity.protobuf.WorldLoginReq}
   */
  public static final class WorldLoginReq extends
      com.google.protobuf.GeneratedMessage
      implements WorldLoginReqOrBuilder {
    // Use WorldLoginReq.newBuilder() to construct.
    private WorldLoginReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WorldLoginReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WorldLoginReq defaultInstance;
    public static WorldLoginReq getDefaultInstance() {
      return defaultInstance;
    }

    public WorldLoginReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WorldLoginReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              type_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              onlineCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wq.entity.protobuf.WorldLogin.internal_static_com_wq_entity_protobuf_WorldLoginReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wq.entity.protobuf.WorldLogin.internal_static_com_wq_entity_protobuf_WorldLoginReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wq.entity.protobuf.WorldLogin.WorldLoginReq.class, com.wq.entity.protobuf.WorldLogin.WorldLoginReq.Builder.class);
    }

    public static com.google.protobuf.Parser<WorldLoginReq> PARSER =
        new com.google.protobuf.AbstractParser<WorldLoginReq>() {
      public WorldLoginReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WorldLoginReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WorldLoginReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>optional int32 type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 type = 3;</code>
     */
    public int getType() {
      return type_;
    }

    // optional int32 onlineCount = 4;
    public static final int ONLINECOUNT_FIELD_NUMBER = 4;
    private int onlineCount_;
    /**
     * <code>optional int32 onlineCount = 4;</code>
     */
    public boolean hasOnlineCount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 onlineCount = 4;</code>
     */
    public int getOnlineCount() {
      return onlineCount_;
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      type_ = 0;
      onlineCount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, onlineCount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, onlineCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wq.entity.protobuf.WorldLogin.WorldLoginReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wq.entity.protobuf.WorldLogin.WorldLoginReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wq.entity.protobuf.WorldLoginReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wq.entity.protobuf.WorldLogin.WorldLoginReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wq.entity.protobuf.WorldLogin.internal_static_com_wq_entity_protobuf_WorldLoginReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wq.entity.protobuf.WorldLogin.internal_static_com_wq_entity_protobuf_WorldLoginReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wq.entity.protobuf.WorldLogin.WorldLoginReq.class, com.wq.entity.protobuf.WorldLogin.WorldLoginReq.Builder.class);
      }

      // Construct using com.wq.entity.protobuf.WorldLogin.WorldLoginReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        onlineCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wq.entity.protobuf.WorldLogin.internal_static_com_wq_entity_protobuf_WorldLoginReq_descriptor;
      }

      public com.wq.entity.protobuf.WorldLogin.WorldLoginReq getDefaultInstanceForType() {
        return com.wq.entity.protobuf.WorldLogin.WorldLoginReq.getDefaultInstance();
      }

      public com.wq.entity.protobuf.WorldLogin.WorldLoginReq build() {
        com.wq.entity.protobuf.WorldLogin.WorldLoginReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wq.entity.protobuf.WorldLogin.WorldLoginReq buildPartial() {
        com.wq.entity.protobuf.WorldLogin.WorldLoginReq result = new com.wq.entity.protobuf.WorldLogin.WorldLoginReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.onlineCount_ = onlineCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wq.entity.protobuf.WorldLogin.WorldLoginReq) {
          return mergeFrom((com.wq.entity.protobuf.WorldLogin.WorldLoginReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wq.entity.protobuf.WorldLogin.WorldLoginReq other) {
        if (other == com.wq.entity.protobuf.WorldLogin.WorldLoginReq.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasOnlineCount()) {
          setOnlineCount(other.getOnlineCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wq.entity.protobuf.WorldLogin.WorldLoginReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wq.entity.protobuf.WorldLogin.WorldLoginReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional int32 type = 3;
      private int type_ ;
      /**
       * <code>optional int32 type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 type = 3;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 3;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      // optional int32 onlineCount = 4;
      private int onlineCount_ ;
      /**
       * <code>optional int32 onlineCount = 4;</code>
       */
      public boolean hasOnlineCount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 onlineCount = 4;</code>
       */
      public int getOnlineCount() {
        return onlineCount_;
      }
      /**
       * <code>optional int32 onlineCount = 4;</code>
       */
      public Builder setOnlineCount(int value) {
        bitField0_ |= 0x00000008;
        onlineCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 onlineCount = 4;</code>
       */
      public Builder clearOnlineCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        onlineCount_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.wq.entity.protobuf.WorldLoginReq)
    }

    static {
      defaultInstance = new WorldLoginReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wq.entity.protobuf.WorldLoginReq)
  }

  public interface WorldLoginResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 result = 1;
    /**
     * <code>optional int32 result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>optional int32 result = 1;</code>
     */
    int getResult();
  }
  /**
   * Protobuf type {@code com.wq.entity.protobuf.WorldLoginRes}
   */
  public static final class WorldLoginRes extends
      com.google.protobuf.GeneratedMessage
      implements WorldLoginResOrBuilder {
    // Use WorldLoginRes.newBuilder() to construct.
    private WorldLoginRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WorldLoginRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WorldLoginRes defaultInstance;
    public static WorldLoginRes getDefaultInstance() {
      return defaultInstance;
    }

    public WorldLoginRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WorldLoginRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wq.entity.protobuf.WorldLogin.internal_static_com_wq_entity_protobuf_WorldLoginRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wq.entity.protobuf.WorldLogin.internal_static_com_wq_entity_protobuf_WorldLoginRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wq.entity.protobuf.WorldLogin.WorldLoginRes.class, com.wq.entity.protobuf.WorldLogin.WorldLoginRes.Builder.class);
    }

    public static com.google.protobuf.Parser<WorldLoginRes> PARSER =
        new com.google.protobuf.AbstractParser<WorldLoginRes>() {
      public WorldLoginRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WorldLoginRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WorldLoginRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>optional int32 result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    private void initFields() {
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wq.entity.protobuf.WorldLogin.WorldLoginRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wq.entity.protobuf.WorldLogin.WorldLoginRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wq.entity.protobuf.WorldLogin.WorldLoginRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wq.entity.protobuf.WorldLoginRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wq.entity.protobuf.WorldLogin.WorldLoginResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wq.entity.protobuf.WorldLogin.internal_static_com_wq_entity_protobuf_WorldLoginRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wq.entity.protobuf.WorldLogin.internal_static_com_wq_entity_protobuf_WorldLoginRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wq.entity.protobuf.WorldLogin.WorldLoginRes.class, com.wq.entity.protobuf.WorldLogin.WorldLoginRes.Builder.class);
      }

      // Construct using com.wq.entity.protobuf.WorldLogin.WorldLoginRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wq.entity.protobuf.WorldLogin.internal_static_com_wq_entity_protobuf_WorldLoginRes_descriptor;
      }

      public com.wq.entity.protobuf.WorldLogin.WorldLoginRes getDefaultInstanceForType() {
        return com.wq.entity.protobuf.WorldLogin.WorldLoginRes.getDefaultInstance();
      }

      public com.wq.entity.protobuf.WorldLogin.WorldLoginRes build() {
        com.wq.entity.protobuf.WorldLogin.WorldLoginRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wq.entity.protobuf.WorldLogin.WorldLoginRes buildPartial() {
        com.wq.entity.protobuf.WorldLogin.WorldLoginRes result = new com.wq.entity.protobuf.WorldLogin.WorldLoginRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wq.entity.protobuf.WorldLogin.WorldLoginRes) {
          return mergeFrom((com.wq.entity.protobuf.WorldLogin.WorldLoginRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wq.entity.protobuf.WorldLogin.WorldLoginRes other) {
        if (other == com.wq.entity.protobuf.WorldLogin.WorldLoginRes.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wq.entity.protobuf.WorldLogin.WorldLoginRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wq.entity.protobuf.WorldLogin.WorldLoginRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 result = 1;
      private int result_ ;
      /**
       * <code>optional int32 result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>optional int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.wq.entity.protobuf.WorldLoginRes)
    }

    static {
      defaultInstance = new WorldLoginRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wq.entity.protobuf.WorldLoginRes)
  }

  public static final int WORLDLOGINREQ_FIELD_NUMBER = 100;
  /**
   * <code>extend .com.wq.entity.protobuf.protocol { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.wq.entity.protobuf.Protocol.protocol,
      com.wq.entity.protobuf.WorldLogin.WorldLoginReq> worldLoginReq = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.wq.entity.protobuf.WorldLogin.WorldLoginReq.class,
        com.wq.entity.protobuf.WorldLogin.WorldLoginReq.getDefaultInstance());
  public static final int WORLDLOGINRES_FIELD_NUMBER = 101;
  /**
   * <code>extend .com.wq.entity.protobuf.protocol { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.wq.entity.protobuf.Protocol.protocol,
      com.wq.entity.protobuf.WorldLogin.WorldLoginRes> worldLoginRes = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.wq.entity.protobuf.WorldLogin.WorldLoginRes.class,
        com.wq.entity.protobuf.WorldLogin.WorldLoginRes.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wq_entity_protobuf_WorldLoginReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wq_entity_protobuf_WorldLoginReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wq_entity_protobuf_WorldLoginRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wq_entity_protobuf_WorldLoginRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020WorldLogin.proto\022\026com.wq.entity.protob" +
      "uf\032\016Protocol.proto\"L\n\rWorldLoginReq\022\n\n\002i" +
      "d\030\001 \002(\005\022\014\n\004name\030\002 \001(\t\022\014\n\004type\030\003 \001(\005\022\023\n\013o" +
      "nlineCount\030\004 \001(\005\"\037\n\rWorldLoginRes\022\016\n\006res" +
      "ult\030\001 \001(\005:^\n\rworldLoginReq\022 .com.wq.enti" +
      "ty.protobuf.protocol\030d \001(\0132%.com.wq.enti" +
      "ty.protobuf.WorldLoginReq:^\n\rworldLoginR" +
      "es\022 .com.wq.entity.protobuf.protocol\030e \001" +
      "(\0132%.com.wq.entity.protobuf.WorldLoginRe" +
      "s"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_wq_entity_protobuf_WorldLoginReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_wq_entity_protobuf_WorldLoginReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wq_entity_protobuf_WorldLoginReq_descriptor,
              new java.lang.String[] { "Id", "Name", "Type", "OnlineCount", });
          internal_static_com_wq_entity_protobuf_WorldLoginRes_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_wq_entity_protobuf_WorldLoginRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wq_entity_protobuf_WorldLoginRes_descriptor,
              new java.lang.String[] { "Result", });
          worldLoginReq.internalInit(descriptor.getExtensions().get(0));
          worldLoginRes.internalInit(descriptor.getExtensions().get(1));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wq.entity.protobuf.Protocol.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
