// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/server/ServerLogin.proto

package com.wq.entity.protobuf.server;

public final class ServerLogin {
  private ServerLogin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.wq.entity.protobuf.server.ServerLogin.worldLoginReq);
    registry.add(com.wq.entity.protobuf.server.ServerLogin.worldLoginRes);
  }
  public interface WorldLoginReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.wq.entity.protobuf.server.WorldLoginReq}
   */
  public static final class WorldLoginReq extends
      com.google.protobuf.GeneratedMessage
      implements WorldLoginReqOrBuilder {
    // Use WorldLoginReq.newBuilder() to construct.
    private WorldLoginReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WorldLoginReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WorldLoginReq defaultInstance;
    public static WorldLoginReq getDefaultInstance() {
      return defaultInstance;
    }

    public WorldLoginReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WorldLoginReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wq.entity.protobuf.server.ServerLogin.internal_static_com_wq_entity_protobuf_server_WorldLoginReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wq.entity.protobuf.server.ServerLogin.internal_static_com_wq_entity_protobuf_server_WorldLoginReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq.class, com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq.Builder.class);
    }

    public static com.google.protobuf.Parser<WorldLoginReq> PARSER =
        new com.google.protobuf.AbstractParser<WorldLoginReq>() {
      public WorldLoginReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WorldLoginReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WorldLoginReq> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wq.entity.protobuf.server.WorldLoginReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wq.entity.protobuf.server.ServerLogin.WorldLoginReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wq.entity.protobuf.server.ServerLogin.internal_static_com_wq_entity_protobuf_server_WorldLoginReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wq.entity.protobuf.server.ServerLogin.internal_static_com_wq_entity_protobuf_server_WorldLoginReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq.class, com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq.Builder.class);
      }

      // Construct using com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wq.entity.protobuf.server.ServerLogin.internal_static_com_wq_entity_protobuf_server_WorldLoginReq_descriptor;
      }

      public com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq getDefaultInstanceForType() {
        return com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq.getDefaultInstance();
      }

      public com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq build() {
        com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq buildPartial() {
        com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq result = new com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq) {
          return mergeFrom((com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq other) {
        if (other == com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.wq.entity.protobuf.server.WorldLoginReq)
    }

    static {
      defaultInstance = new WorldLoginReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wq.entity.protobuf.server.WorldLoginReq)
  }

  public interface WorldLoginResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 serverId = 1;
    /**
     * <code>required int32 serverId = 1;</code>
     */
    boolean hasServerId();
    /**
     * <code>required int32 serverId = 1;</code>
     */
    int getServerId();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional int32 type = 3;
    /**
     * <code>optional int32 type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>optional int32 type = 3;</code>
     */
    int getType();

    // optional string ip = 4;
    /**
     * <code>optional string ip = 4;</code>
     */
    boolean hasIp();
    /**
     * <code>optional string ip = 4;</code>
     */
    java.lang.String getIp();
    /**
     * <code>optional string ip = 4;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    // optional int32 port = 5;
    /**
     * <code>optional int32 port = 5;</code>
     */
    boolean hasPort();
    /**
     * <code>optional int32 port = 5;</code>
     */
    int getPort();

    // optional int32 onlineCount = 6;
    /**
     * <code>optional int32 onlineCount = 6;</code>
     */
    boolean hasOnlineCount();
    /**
     * <code>optional int32 onlineCount = 6;</code>
     */
    int getOnlineCount();

    // optional int64 updateTime = 7;
    /**
     * <code>optional int64 updateTime = 7;</code>
     */
    boolean hasUpdateTime();
    /**
     * <code>optional int64 updateTime = 7;</code>
     */
    long getUpdateTime();
  }
  /**
   * Protobuf type {@code com.wq.entity.protobuf.server.WorldLoginRes}
   */
  public static final class WorldLoginRes extends
      com.google.protobuf.GeneratedMessage
      implements WorldLoginResOrBuilder {
    // Use WorldLoginRes.newBuilder() to construct.
    private WorldLoginRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WorldLoginRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WorldLoginRes defaultInstance;
    public static WorldLoginRes getDefaultInstance() {
      return defaultInstance;
    }

    public WorldLoginRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WorldLoginRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              type_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              ip_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              port_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              onlineCount_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              updateTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wq.entity.protobuf.server.ServerLogin.internal_static_com_wq_entity_protobuf_server_WorldLoginRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wq.entity.protobuf.server.ServerLogin.internal_static_com_wq_entity_protobuf_server_WorldLoginRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes.class, com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes.Builder.class);
    }

    public static com.google.protobuf.Parser<WorldLoginRes> PARSER =
        new com.google.protobuf.AbstractParser<WorldLoginRes>() {
      public WorldLoginRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WorldLoginRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WorldLoginRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 serverId = 1;
    public static final int SERVERID_FIELD_NUMBER = 1;
    private int serverId_;
    /**
     * <code>required int32 serverId = 1;</code>
     */
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 serverId = 1;</code>
     */
    public int getServerId() {
      return serverId_;
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>optional int32 type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 type = 3;</code>
     */
    public int getType() {
      return type_;
    }

    // optional string ip = 4;
    public static final int IP_FIELD_NUMBER = 4;
    private java.lang.Object ip_;
    /**
     * <code>optional string ip = 4;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string ip = 4;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ip = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 port = 5;
    public static final int PORT_FIELD_NUMBER = 5;
    private int port_;
    /**
     * <code>optional int32 port = 5;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 port = 5;</code>
     */
    public int getPort() {
      return port_;
    }

    // optional int32 onlineCount = 6;
    public static final int ONLINECOUNT_FIELD_NUMBER = 6;
    private int onlineCount_;
    /**
     * <code>optional int32 onlineCount = 6;</code>
     */
    public boolean hasOnlineCount() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 onlineCount = 6;</code>
     */
    public int getOnlineCount() {
      return onlineCount_;
    }

    // optional int64 updateTime = 7;
    public static final int UPDATETIME_FIELD_NUMBER = 7;
    private long updateTime_;
    /**
     * <code>optional int64 updateTime = 7;</code>
     */
    public boolean hasUpdateTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 updateTime = 7;</code>
     */
    public long getUpdateTime() {
      return updateTime_;
    }

    private void initFields() {
      serverId_ = 0;
      name_ = "";
      type_ = 0;
      ip_ = "";
      port_ = 0;
      onlineCount_ = 0;
      updateTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getIpBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, port_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, onlineCount_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, updateTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getIpBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, port_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, onlineCount_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, updateTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wq.entity.protobuf.server.WorldLoginRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wq.entity.protobuf.server.ServerLogin.WorldLoginResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wq.entity.protobuf.server.ServerLogin.internal_static_com_wq_entity_protobuf_server_WorldLoginRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wq.entity.protobuf.server.ServerLogin.internal_static_com_wq_entity_protobuf_server_WorldLoginRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes.class, com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes.Builder.class);
      }

      // Construct using com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        onlineCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        updateTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wq.entity.protobuf.server.ServerLogin.internal_static_com_wq_entity_protobuf_server_WorldLoginRes_descriptor;
      }

      public com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes getDefaultInstanceForType() {
        return com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes.getDefaultInstance();
      }

      public com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes build() {
        com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes buildPartial() {
        com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes result = new com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.onlineCount_ = onlineCount_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.updateTime_ = updateTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes) {
          return mergeFrom((com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes other) {
        if (other == com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes.getDefaultInstance()) return this;
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000008;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasOnlineCount()) {
          setOnlineCount(other.getOnlineCount());
        }
        if (other.hasUpdateTime()) {
          setUpdateTime(other.getUpdateTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 serverId = 1;
      private int serverId_ ;
      /**
       * <code>required int32 serverId = 1;</code>
       */
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 serverId = 1;</code>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>required int32 serverId = 1;</code>
       */
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000001;
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverId = 1;</code>
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional int32 type = 3;
      private int type_ ;
      /**
       * <code>optional int32 type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 type = 3;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 3;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      // optional string ip = 4;
      private java.lang.Object ip_ = "";
      /**
       * <code>optional string ip = 4;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string ip = 4;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ip = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 4;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 4;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 4;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ip_ = value;
        onChanged();
        return this;
      }

      // optional int32 port = 5;
      private int port_ ;
      /**
       * <code>optional int32 port = 5;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 port = 5;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>optional int32 port = 5;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000010;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 port = 5;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000010);
        port_ = 0;
        onChanged();
        return this;
      }

      // optional int32 onlineCount = 6;
      private int onlineCount_ ;
      /**
       * <code>optional int32 onlineCount = 6;</code>
       */
      public boolean hasOnlineCount() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 onlineCount = 6;</code>
       */
      public int getOnlineCount() {
        return onlineCount_;
      }
      /**
       * <code>optional int32 onlineCount = 6;</code>
       */
      public Builder setOnlineCount(int value) {
        bitField0_ |= 0x00000020;
        onlineCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 onlineCount = 6;</code>
       */
      public Builder clearOnlineCount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        onlineCount_ = 0;
        onChanged();
        return this;
      }

      // optional int64 updateTime = 7;
      private long updateTime_ ;
      /**
       * <code>optional int64 updateTime = 7;</code>
       */
      public boolean hasUpdateTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 updateTime = 7;</code>
       */
      public long getUpdateTime() {
        return updateTime_;
      }
      /**
       * <code>optional int64 updateTime = 7;</code>
       */
      public Builder setUpdateTime(long value) {
        bitField0_ |= 0x00000040;
        updateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 updateTime = 7;</code>
       */
      public Builder clearUpdateTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        updateTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.wq.entity.protobuf.server.WorldLoginRes)
    }

    static {
      defaultInstance = new WorldLoginRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wq.entity.protobuf.server.WorldLoginRes)
  }

  public static final int WORLDLOGINREQ_FIELD_NUMBER = 100;
  /**
   * <code>extend .com.wq.entity.protobuf.protocol { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.wq.entity.protobuf.Protocol.protocol,
      com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq> worldLoginReq = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq.class,
        com.wq.entity.protobuf.server.ServerLogin.WorldLoginReq.getDefaultInstance());
  public static final int WORLDLOGINRES_FIELD_NUMBER = 101;
  /**
   * <code>extend .com.wq.entity.protobuf.protocol { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.wq.entity.protobuf.Protocol.protocol,
      com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes> worldLoginRes = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes.class,
        com.wq.entity.protobuf.server.ServerLogin.WorldLoginRes.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wq_entity_protobuf_server_WorldLoginReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wq_entity_protobuf_server_WorldLoginReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wq_entity_protobuf_server_WorldLoginRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wq_entity_protobuf_server_WorldLoginRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036proto/server/ServerLogin.proto\022\035com.wq" +
      ".entity.protobuf.server\032\024proto/Protocol." +
      "proto\"\017\n\rWorldLoginReq\"\200\001\n\rWorldLoginRes" +
      "\022\020\n\010serverId\030\001 \002(\005\022\014\n\004name\030\002 \001(\t\022\014\n\004type" +
      "\030\003 \001(\005\022\n\n\002ip\030\004 \001(\t\022\014\n\004port\030\005 \001(\005\022\023\n\013onli" +
      "neCount\030\006 \001(\005\022\022\n\nupdateTime\030\007 \001(\003:e\n\rwor" +
      "ldLoginReq\022 .com.wq.entity.protobuf.prot" +
      "ocol\030d \001(\0132,.com.wq.entity.protobuf.serv" +
      "er.WorldLoginReq:e\n\rworldLoginRes\022 .com." +
      "wq.entity.protobuf.protocol\030e \001(\0132,.com.",
      "wq.entity.protobuf.server.WorldLoginRes"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_wq_entity_protobuf_server_WorldLoginReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_wq_entity_protobuf_server_WorldLoginReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wq_entity_protobuf_server_WorldLoginReq_descriptor,
              new java.lang.String[] { });
          internal_static_com_wq_entity_protobuf_server_WorldLoginRes_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_wq_entity_protobuf_server_WorldLoginRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wq_entity_protobuf_server_WorldLoginRes_descriptor,
              new java.lang.String[] { "ServerId", "Name", "Type", "Ip", "Port", "OnlineCount", "UpdateTime", });
          worldLoginReq.internalInit(descriptor.getExtensions().get(0));
          worldLoginRes.internalInit(descriptor.getExtensions().get(1));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wq.entity.protobuf.Protocol.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
